/* Expected output of `_pct` in playbook/evals/report.py for each value, so the self-check compares
   the ported percent formatting with Python's own output instead of with a second implementation
   of its rounding rules.

   Generated by: uv run python scripts/pct-cases.py > web/src/fixtures/pct-cases.ts */
export type PctCase = [value: number, expected: string];

export const PCT_CASES: PctCase[] = [
  [0.0, "0.0%"],
  [0.125, "12.5%"],
  [0.1235, "12.3%"],
  [0.4375, "43.8%"],
  [0.5625, "56.2%"],
  [0.875, "87.5%"],
  [0.9865, "98.7%"],
  [1.0, "100.0%"],
  [0.3333333333333333, "33.3%"],
  [0.6666666666666666, "66.7%"],
  [-0.5625, "-56.2%"],
  [-0.4375, "-43.8%"],
];
